# ===================================
#  Relation Behavior Config
# ===================================

posts:
    label: Posts
    list: ~/plugins/rainlab/blog/models/post/columns.yaml
    form: ~/plugins/rainlab/blog/models/post/fields.yaml
    view:
        toolbarButtons: add|remove
        recordsPerPage: 10
        showSearch: true
    manage:
        recordsPerPage: 10
        context: relation
